config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: 'users'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'devise/registrations#new'
  end
  devise_for :admins, :skip => [:registrations], path: 'admins'
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  namespace :admin do
    resources :sellers, only:[:new, :index, :create, :edit, :update, :destroy, :show] do
      collection do
        get 'states'
        get 'load_size_values'
      end
    end
    resources :pallets, only: [:update]
    resources :categories, only:[:new, :index, :create, :edit, :update, :destroy] do
      collection do
        get "load_size_types"
      end
    end
    resources :dashboard, only:[:index]
    #resources :products, only:[:index, :new, :create, :edit, :update, :show]
    resources :option_types, only:[:index, :new, :create, :edit, :update]
    resources :users, only: [:index, :show] do
      member do
        get 'approve'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      member do
        get 'cancel_order'
        get 'paid_order'
        get 'change_delivery_status'
      end
      collection do
        get 'public_orders', as: "public"
      end
    end
    root to: "categories#index"
    # get 'sellers/states'
  end
  resource :user, only: [:edit, :update] do
    collection do
      get "new_address"
      post "create_address"
      get "edit_address"
      patch "update_address"
      get 'delete_address'
    end
  end
  resources :notifications, only:[:index]
  resources :orders, only: [:new, :create] do
    collection do
      get 'select_category'
      get 'my_requests'
      get 'my_orders'
      post "hook"
      get 'order_summary'
      get 'order_canceled'
      get 'get_pallet'
      get 'ask_with_comparator'
    end
    member do
      get 'cancel_order', as: "cancel"
      get 'invoice'
      get 'offer_summary'
    end
  end
  get '/orders', to: 'orders#my_requests'
  get 'categories/index'
  get 'categories/states'
  get '/home/contact_us'
  get '/home/privacy'
  get '/home/faq'
  get '/home/how_it_works'
  get '/home/home_page'
  get '/home/comparator'
  get '/home/get_sellers'
  post '/home/send_message'

  root to: "home#home_page"
  match '*path', via: :all, to: redirect('/404')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :category, -> { with_deleted }
  belongs_to :user
  belongs_to :seller, -> { with_deleted }
  has_many :order_values, dependent: :destroy
  has_many :option_values, through: :order_values
  belongs_to :billing_address, -> { with_deleted }, :class_name => "Address", :foreign_key => "billing_id"
  belongs_to :shipping_address,-> { with_deleted }, :class_name => "Address", :foreign_key => "shipping_id"
  after_save :generate_random_id
  serialize :notification_params
  validates :quantity, presence: true, numericality: {only_integer: true}
  # validates :delay, numericality: { only_integer: true }, on: :update
  # validates :price, numericality: { only_integer: true }, on: :update
  # validates :price, :presence => true, :format => { :with => /^(\$)?(\d+)(\.|,)?\d{0,2}?$/ }

  def paypal_url(return_url, notification_url, cancel_url)
    values = {
     business: 'vishnu.demo@gmail.com',
     cmd: "_xclick",
     upload: 1,
     return: return_url,
     invoice: id,
     currency_code: 'EUR',
     amount: price,
     item_name: order_id,
     quantity: '1',
     cancel_return_url: cancel_url,
     notify_url: notification_url
    }
    # For test transactions use this URL
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    # "https://www.paypal.com/cgi-bin/webscr?&#8221;" + values.to_query
  end

  def self.pre_order_status(status)
    if status == "Approved"
      where(approved: true, canceled: false)
    elsif status == "Cancelled"
      where(canceled: true)
    elsif status == "Pending"
      where(canceled: false, approved: false)
    else
      where("1 = 0")
    end
  end

  def offer_name
    self.order_id.gsub "ORDER", "OFFER"
  end

  def self.ransackable_scopes(auth_object = nil)
    %i(pre_order_status)
  end

  def difference
    if price.present? && total_price.present?
      total_price - price
    else
      ""
    end
  end

  def admin_status
    if self.canceled?
      "Cancelled"
    elsif self.approved?
      "Approved"
    elsif self.expired?
      "Expired"
    else
      "Pending"
    end
  end

  def payment_status
    if self.transaction_id?
      "Paid"
    else
      "Not paid"
    end
  end

  def normal_price
    total_price/total_quantity
  end

  def discount_price
    price/total_quantity
  end

  def expired?
    if self.expires_at && (self.expires_at < Time.now)
      true
    else
      false
    end
  end

  def total_quantity
    quantity*pallets
  end

  def options
    self.option_values.with_deleted.map(&:presentation.downcase).join(", ").titleize
  end

  def delivery_status
    delivered ? "Delivered": "Undelivered"
  end

  private

  def generate_random_id
    return if order_id.present?
    order_id = "ORDER"+"#{rand(9999)}"+"#{self.id}"
    self.update_attributes(order_id: order_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = Order.ransack(params[:q])
    @orders = @q.result.includes(:user, :category).where(accepted: false).order(created_at: :desc).page(params[:page]).per(20)
  end

  def public_orders
    @q = Order.ransack(params[:q])
    @orders = @q.result.includes(:user, :category).where(approved: true, accepted: true, canceled: false).order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @order = Order.find(params[:id])
    @shipping = @order.shipping_address
    @billing = @order.shipping_address
  end

  def paid_order
    @order = Order.find(params[:id])
    @shipping = @order.shipping_address
    @billing = @order.shipping_address
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "Offer notifications sent to user"
      OrderMailer.approved(@order).deliver_now
      redirect_to admin_orders_path
    else
      flash[:notice] = "Something went wrong"
    end
  end

  def cancel_order
    @order = Order.find(params[:id])
    @order.update(canceled: true)
    OrderMailer.canceled(@order).deliver_now
    redirect_to admin_orders_path
  end

  def change_delivery_status
    @order = Order.find(params[:id])
    @order.delivered = !@order.delivered
    @order.save
    respond_to do |format|
      format.js
    end
  end

  def order_params
    params.require(:order).permit(:price, :delay, :total_price, :delivery_charge).merge(approved: true, expires_at: 30.days.from_now)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "frontend"
  before_action :authenticate_user!, except: :hook
  skip_before_action :verify_authenticity_token, only: :hook
  # load_and_authorize_resource

  def select_category
    authorize! :select_category, Order, :message => "You are not verified by Tradepack"
    @categories = Category.size_categories
  end

  def new
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @sellers = @category.pallet_sellers
      @option_types = @category.option_types
      @count = @option_types.count
      @addresses = current_user.addresses
      @size_id = @category.size_type.id
      @order = Order.new
    else
      redirect_to select_category_orders_path
    end
  end

  def create
    @order = Order.new(order_params)
    @order.option_value_ids = params[:order][:option_value_ids].values
    if @order.save
      flash[:notice] = "Order request is successfully placed"
      redirect_to my_requests_orders_path
    else
      flash[:danger] = "Something went wrong"
      redirect_to select_category_orders_path
    end
  end

  def ask_with_comparator
    @category = Category.find(params[:category_id])
    @seller = Seller.find(params[:seller_id])
    @option_types = @category.option_types
    @count = @option_types.count
    @addresses = current_user.addresses
    @size_id = @category.size_type.id
    @order = Order.new
  end

  def my_requests
    @orders = current_user.orders.includes(:seller, :shipping_address, :category).where(accepted: false).order(created_at: :desc)
  end

  def my_orders
    @orders = current_user.orders.includes(:seller, :shipping_address, :category).where(accepted: true, canceled: false).where.not(transaction_id: nil).order(created_at: :desc)
  end

  def index
    @orders = current_user.orders.where(accepted: false)
  end

  def cancel_order
    @order = Order.find(params[:id])
    @order.update(canceled: true, cancelled_by: "user")
    redirect_to my_requests_orders_path
  end

  def offer_summary
    @order = Order.find(params[:id])
  end

  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @order = Order.find(params[:invoice])
      date = Date.today + @order.delay
      @order.update_attributes(notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now, accepted: true, delivery_date: date)
      OrderMailer.order_placed(@order).deliver_now
    end
    render body: nil
  end

  def invoice
    @order = Order.find(params[:id])
    respond_to do |format|
      format.pdf do
        render :pdf => "report"
      end
    end
  end

  def order_summary
    @order = Order.find(params[:id])
  end

  def order_canceled
  end

  def get_pallet
    @category = Category.find(params[:category_id])
    @pallet = Pallet.find_by(category_id: params[:category_id], seller_id: params[:seller_id], option_value_id: params[:value_id])
    if @pallet.present?
      respond_to do |format|
        format.js
      end
    else
      render body: nil
    end
  end

  private

  def order_params
    params.require(:order).permit(:category_id, :quantity, :seller_id, :shipping_id, :pallets, :billing_id, {option_value_ids: []}).merge(user_id: current_user.id)
  end

end

app/views/admin/orders/_select_tag.html.erb
<%= select_tag "delivery_status", options_for_select([ "Delivered", "Undelivered" ], @order.delivery_status), class: "status-#{check_delivery(@order)} select-status", onchange: "change_delivery_status(#{@order.id})"%>

app/views/admin/orders/change_delivery_status.js.erb
$("#delivery_<%=@order.id%>").html("<%= j render 'select_tag' %>");

app/views/admin/orders/index.html.erb
  <div class="container-fluid">

    <div class="page-toolbar">

      <div class="page-toolbar-block">
        <div class="page-toolbar-title"> Pre-orders List</div>
        <div class="page-toolbar-subtitle">Subtitle</div>
      </div>

      <ul class="breadcrumb">
        <li><a href="<%= admin_root_path %>">Dashboard</a></li>
        <li class="active">Pre-orders</li>
      </ul>

    </div>

    <div class="clearfix"></div>

    <div class="page-wrapper">
      <div class="container-fluid">

        <%= search_form_for @q, url: admin_orders_path do |f| %>
          <div class="col-sm-3">
            <%= f.select :category_title_cont, options_from_collection_for_select(Category.all, "title", "title"), {include_blank: "Select Category"},{class: "form-control"}%>
          </div>
          <div class="col-sm-3">
            <%= f.search_field :user_first_name_cont, placeholder: "User", class: "form-control"  %>
          </div>
          <div class="col-sm-3">
            <%=f.select :pre_order_status, [['Approved', 'Approved'], ['Pending', 'Pending'], ['Canceled', 'Canceled']], {include_blank: "Select Status"} ,class: "form-control"%>
          </div>
            <div class="col-sm-3 mb20">
              <%= link_to request.path, class: "btn btn-primary " do %>
                <i class="fas fa-filter"></i> Clear Filter
              <% end %>
              <%= f.button :submit, class: "btn btn-success ml10" do %>
                <i class='fas fa-search'></i> Search
              <% end %>
            </div>
        <% end %>


        <table class="table list">
          <thead>
            <tr>
              <th>Order Id</th>
              <th>Category</th>
              <th>User</th>
              <th>No of pallets</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= link_to order.order_id, admin_order_path(order)%></td>
                <td><%= order.category.title.titleize %></td>
                <td><%= order.user.full_name %></td>
                <td><%= order.pallets %></td>
                <td class="">
                 <a class="<%=admin_status(order.admin_status)%>" href="javascript:void(0)"><%= order.admin_status %>
                </a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @orders %>
      </div>
    </div>
  </div>

app/views/admin/orders/public_orders.html.erb
  <div class="container-fluid">

    <div class="page-toolbar">

      <div class="page-toolbar-block">
        <div class="page-toolbar-title"> Public-Orders List</div>
        <div class="page-toolbar-subtitle">Subtitle</div>
      </div>

      <ul class="breadcrumb">
        <li><a href="<%= admin_root_path %>">Dashboard</a></li>
        <li class="active">Public-orders</li>
      </ul>

    </div>

    <div class="clearfix"></div>

    <div class="page-wrapper">
      <div class="container-fluid">

        <%= search_form_for @q, url: public_admin_orders_path do |f| %>
          <div class="col-sm-3">
            <%= f.select :category_title_cont, options_from_collection_for_select(Category.all, "title", "title"), {include_blank: "Select Category"},{class: "form-control"}%>
          </div>
          <div class="col-sm-3">
            <%= f.search_field :user_first_name_cont, placeholder: "User", class: "form-control"  %>
          </div>
          <!-- <div class="col-sm-3">
            <%#= f.search_field :company_cont, placeholder: "Company", class: "form-control"  %>
          </div> -->
            <div class="col-sm-3 mb20">
              <%= link_to request.path, class: "btn btn-primary " do %>
                <i class="fas fa-filter"></i> Clear Filter
              <% end %>
              <%= f.button :submit, class: "btn btn-success ml10" do %>
                <i class='fas fa-search'></i> Search
              <% end %>
            </div>
        <% end %>


        <table class="table list">
          <thead>
            <tr>
              <th>Order Id</th>
              <th>Category</th>
              <th>User</th>
              <th>No of pallets</th>
              <th>Status</th>
              <th>Payment Status</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= link_to order.order_id, paid_order_admin_order_path(order)%></td>
                <td><%= order.category.title.titleize %></td>
                <td><%= order.user.full_name %></td>
                <td><%= order.pallets %></td>
                <td><%= order.payment_status%></td>
                <td id="delivery_<%=order.id%>">
                  <%= select_tag "delivery_status", options_for_select([ "Delivered", "Undelivered" ], order.delivery_status), class: "status-#{check_delivery(order)} select-status", onchange: "change_delivery_status(#{order.id})"%>
                </td>

              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @orders %>
      </div>
    </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="container-fluid">
 <div class="page-toolbar">

  <div class="page-toolbar-block">
    <div class="page-toolbar-title"> Pre-Order Details</div>
    <div class="page-toolbar-subtitle">Subtitle</div>
  </div>

  <ul class="breadcrumb">
    <li><a href="<%= admin_root_path %>">Dashboard</a></li>
    <li class="active">Order</li>
  </ul>

</div>

<div class="col-sm-8 col-sm-offset-2 ">
  <h3 class="p-color">Order Details</h3>
  <div class="users-view mt20 row">
    <div class="col-sm-6">
      <p> <b>Order Id</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.order_id%></p>
    </div>
    <div class="col-sm-6">
      <p> <b>Category</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.category.title.titleize%></p>
    </div>
    <% @order.option_values.includes(:option_type).with_deleted.each do |value| %>
     <div class="col-sm-6">
      <p> <b><%=value.option_type.name%></b> <span class="pull-right">: </span> </p>
      </div>
      <div class="col-sm-6">
        <p><%= value.name.titleize %></p>
      </div>
    <% end %>
    <div class="col-sm-6">
     <p> <b>Pallet Quantity</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%= @order.total_quantity  %>&nbsp(<%= @order.pallets%> x <%=@order.quantity%>)</p>
     </div>
  </div>

 <h3 class="p-color">User Details</h3>
  <div class="users-view mt20 row">
    <div class="col-sm-6">
      <p> <b>Name</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.user.full_name.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Email</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.user.email%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Company</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.user.company.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Phone</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.user.phone_no%></p>
    </div>

  </div>

  <h3 class="p-color">Seller Details</h3>
  <div class="users-view mt20 row">
    <div class="col-sm-6">
      <p> <b>Seller</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.seller.name.titleize%></p>
    </div>
    <div class="col-sm-6">
      <p> <b>Email</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@order.seller.email%></p>
    </div>
    <div class="col-sm-6">
     <p> <b>Phone</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%= @order.seller.phone_no %></p>
     </div>
     <div class="col-sm-6">
       <p> <b>Vat Number</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%= @order.seller.vat_no %></p>
     </div>
  </div>


 <h3 class="p-color">Shipping Address </h3>
  <div class="users-view mt20 row">
    <div class="col-sm-6">
      <p> <b>Name</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.name.titleize|| "Nil"%></p>
    </div>
    <div class="col-sm-6">
      <p> <b>Street/Number</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.address1.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Box</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.address2.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Locality/Town</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.city.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>State</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.state.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Country</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.country.titleize%></p>
    </div>

    <div class="col-sm-6">
      <p> <b>Postal Code</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.zip%></p>
    </div>
    <div class="col-sm-6">
      <p> <b>Phone</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@shipping.phone_no|| "Nil"%></p>
    </div>
  </div>

  <h3 class="p-color">Billing Address </h3>
   <div class="users-view mt20 row">
    <div class="col-sm-6">
      <p> <b>Name</b> <span class="pull-right">: </span> </p>
    </div>
    <div class="col-sm-6">
      <p><%=@billing.name.titleize|| "Nil"%></p>
    </div>
     <div class="col-sm-6">
       <p> <b>Street/Number</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.address1.titleize%></p>
     </div>

     <div class="col-sm-6">
       <p> <b>Box</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.address2.titleize%></p>
     </div>

     <div class="col-sm-6">
       <p> <b>Locality/Town</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.city.titleize%></p>
     </div>

     <div class="col-sm-6">
       <p> <b>State</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.state.titleize%></p>
     </div>

     <div class="col-sm-6">
       <p> <b>Country</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.country.titleize%></p>
     </div>

     <div class="col-sm-6">
       <p> <b>Postal Code</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.zip%></p>
     </div>
     <div class="col-sm-6">
       <p> <b>Phone</b> <span class="pull-right">: </span> </p>
     </div>
     <div class="col-sm-6">
       <p><%=@billing.phone_no|| "Nil"%></p>
     </div>
   </div>


  <% if @order.approved? %>
  <h3 class="p-color">Fix Amount/Delivery </h3>
    <div class="users-view mt20 row">
      <div class="col-sm-6">
        <p class="mt20"> <b>Total Amount</b> <span class="pull-right">: </span> </p>
      </div>
      <div class="col-sm-6">
        <p><%= text_field_tag "total_price",@order.total_price, class: "form-control amount-input", placeholder: "Enter amount for one product", readonly: true , id: "total-price", required: true%></p>
      </div>
      <div class="col-sm-6">
        <p class="mt20"> <b> Fixed Amount</b> <span class="pull-right">: </span> </p>
      </div>
      <div class="col-sm-6">
        <p><%= text_field_tag "price",@order.price, class: "form-control amount-input", placeholder: "Enter amount for this order", max: "#total-price", readonly: true %></p>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <p class="mt20"> <b>Delivery Delay</b> <span class="pull-right">: </span> </p>
      </div>
      <div class="col-sm-6">
        <p><%= text_field_tag "delay", @order.delay, class: "form-control amount-input", placeholder: "Enter delivery delay in days", digits: true, required: true, readonly: true%></p>
      </div>
    </div>

  <% elsif @order.canceled %>
  <h3 class="p-color">Fix Amount/Delivery/Status </h3>
    <div class="users-view mt20 row">
      <div class="col-sm-6">
        <p> <b> Status</b> <span class="pull-right">: </span> </p>
      </div>
      <div class="col-sm-6">
        <p>Cancelled</p>
      </div>
    </div>

  <% else %>
    <h3 class="p-color">Fix Amount/Delivery </h3>
    <div class="users-view mt20 row">
      <%= form_for @order, url: admin_order_path, method: :put, html: {id: "fix_price"} do |f| %>
        <%= render 'shared/errors', object: f.object %>
        <div class="col-sm-6">
          <p class="mt20"> <b>Price/Product</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= text_field_tag "product_price","", class: "form-control amount-input", placeholder: "Enter amount for one product", id: "normal_price", required: true, number: true, min: 0.01 %></p>
        </div>
        <div class="col-sm-6">
          <p class="mt20"> <b>Total Amount</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= f.text_field :total_price, class: "form-control amount-input", placeholder: "Enter Total Amount", readonly: true , id: "total-price", required: true%></p>
        </div>
        <div class="col-sm-6">
          <p class="mt20"> <b>Discount Price/Product</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= text_field_tag "discount_price","", class: "form-control amount-input", placeholder: "Enter Discount Price", id: "discount_price", required: true %></p>
        </div>
        <div class="col-sm-6">
          <p class="mt20"> <b> Total Discount Price</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= f.text_field :price, class: "form-control amount-input", placeholder: "Enter Total Discount Price", max: "#total-price", id: "total_discount_price", readonly: true %></p>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
          <p class="mt20"> <b>Delivery Charge</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= f.text_field :delivery_charge, class: "form-control amount-input", placeholder: "Enter Delivery Charge", id: "delivery_charge", required: true, number: true, value: "0"%></p>
        </div>
        <div class="col-sm-6">
          <p class="mt20"> <b>Total Price</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= text_field_tag "product_price","", class: "form-control amount-input", placeholder: "Enter Total Price", id: "product_total_price", required: true, readonly: true, number: true, required: true %></p>
        </div>
        <div class="col-sm-6">
          <p class="mt20"> <b>Delivery Delay</b> <span class="pull-right">: </span> </p>
        </div>
        <div class="col-sm-6">
          <p><%= f.text_field :delay, class: "form-control amount-input", placeholder: "Enter delivery delay in days", digits: true, required: true %></p>
        </div>
        <div align="right">
          <%= link_to "Back", admin_orders_path, class: "btn  mt15 mr10" %>
          <%= link_to "Cancel Order", cancel_order_admin_order_path(@order), class: "btn btn-default mt15 mr10" %>
          <button class="btn btn-primary mt15">Approve</button>
      <% end %>
    </div>
  <% end %>
</div>
</div>

</div>

</div>
<script>
  $(document).ready(function(){
    $("#fix_price").validate({
      rules: {
        "order[price]": {
          required: true,
          pattern: /^\d{0,8}(\.\d{1,4})?$/,
          max: function(){ return parseInt($("#total-price").val());}
        }
      }
    });

    $('#normal_price').keyup(function() {
        var dInput = this.value;
        $("#total-price").val(dInput*<%=@order.quantity * @order.pallets%>);
    });
    $('#discount_price').keyup(function() {
        var dInput = this.value;
        $("#total_discount_price").val(dInput*<%=@order.quantity * @order.pallets%>);
    });

    $('#delivery_charge, #discount_price').keyup(function() {
        var second = $("#delivery_charge").val();
        var first = $("#total_discount_price").val();
        var result = parseFloat(second) + parseFloat(first);
        if (!isNaN(result)) {
          $("#product_total_price").val(result);
        }
    });
  });
</script>