config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: 'users'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'devise/registrations#new'
  end
  devise_for :admins, :skip => [:registrations], path: 'admins'
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  namespace :admin do
    resources :sellers, only:[:new, :index, :create, :edit, :update, :destroy, :show] do
      collection do
        get 'states'
        get 'load_size_values'
      end
    end
    resources :pallets, only: [:update]
    resources :categories, only:[:new, :index, :create, :edit, :update, :destroy] do
      collection do
        get "load_size_types"
      end
    end
    resources :dashboard, only:[:index]
    #resources :products, only:[:index, :new, :create, :edit, :update, :show]
    resources :option_types, only:[:index, :new, :create, :edit, :update]
    resources :users, only: [:index, :show] do
      member do
        get 'approve'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      member do
        get 'cancel_order'
        get 'paid_order'
        get 'change_delivery_status'
      end
      collection do
        get 'public_orders', as: "public"
      end
    end
    root to: "categories#index"
    # get 'sellers/states'
  end
  resource :user, only: [:edit, :update] do
    collection do
      get "new_address"
      post "create_address"
      get "edit_address"
      patch "update_address"
      get 'delete_address'
    end
  end
  resources :notifications, only:[:index]
  resources :orders, only: [:new, :create] do
    collection do
      get 'select_category'
      get 'my_requests'
      get 'my_orders'
      post "hook"
      get 'order_summary'
      get 'order_canceled'
      get 'get_pallet'
      get 'ask_with_comparator'
    end
    member do
      get 'cancel_order', as: "cancel"
      get 'invoice'
      get 'offer_summary'
    end
  end
  get '/orders', to: 'orders#my_requests'
  get 'categories/index'
  get 'categories/states'
  get '/home/contact_us'
  get '/home/privacy'
  get '/home/faq'
  get '/home/how_it_works'
  get '/home/home_page'
  get '/home/comparator'
  get '/home/get_sellers'
  post '/home/send_message'

  root to: "home#home_page"
  match '*path', via: :all, to: redirect('/404')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!
  layout "frontend"

  def home_page
  end

  def contact_us
    @message = ContactMessage.new
  end

  def send_message
    @message = ContactMessage.new(message_params)
    if @message.valid?
      ContactMailer.contact(@message).deliver_now
      redirect_to home_contact_us_path
      flash[:notice] = "We have received your message and will be in touch soon!"
    else
      flash[:notice] = "There was an error sending your message. Please try again."
      redirect_to home_contact_us_path
    end
  end

  def privacy
  end

  def how_it_works
  end

  def comparator
    authorize! :comparator, Order, :message => "You are not verified by Tradepack"
    @categories = Category.size_categories
    @category = @categories.first
    @sellers = @category.pallet_sellers if @category.present?
  end

  def get_sellers
    @category = Category.find(params[:id])
    @sellers = @category.pallet_sellers if @category.present?
    respond_to do |format|
      format.js
    end
  end

  def faq
  end

  private

  def message_params
    params.require(:contact_message).permit(:name, :email, :body)
  end

end

app/views/home/_seller_comparator.html.erb
<div class="owl-carousel owl-theme">
  <% sellers.each do |seller| %>
    <div class="item">
      <div class="com-box">
        <%= image_tag (seller.logo.url) %>
        <div class="divide">
          <h4><b><%= seller.name.titleize %></b></h4>
          <p><%= seller.email%></p>
        </div>
        <% category.option_types.each do |type| %>
          <div class="divide">
            <h4><b><%=type.presentation.titleize %></b></h4>
            <p><%= type.joined_values %></p>
          </div>
        <% end %>
        <div class="divide">
          <%= link_to "Ask request", ask_with_comparator_orders_path(category_id: category.id, seller_id: seller.id), class: "btn-main btn" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function () {
    $('.owl-carousel').owlCarousel({
      loop:true,
      margin:15,
      responsiveClass:true,
      navigation:true,
      autoplay:true,
      responsive:{
        0:{
          items:1,
          nav:true
        },
        600:{
          items:3,
          nav:false
        },
        1000:{
          items:5,
          nav:true,
          loop:true
        }
      }
    })
  });
</script>

app/views/home/comparator.html.erb
<div class="compat">
  <% if @sellers.present? %>
    <div class="container">
      <%= select_tag "category", options_from_collection_for_select(@categories, 'id', "title_to_upper"), class: "form-control", onchange: "get_sellers(value)"%>
      <div id= "comparator_page">
        <%= render partial: 'seller_comparator',locals: {category: @category, sellers: @sellers} %>
      </div>
    </div>
  <% else %>
    <h3>Nothing to show</h3>
  <% end %>
</div>

app/views/home/contact_us.html.erb
<div class="contact-us">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h2>We are eager to discuss your business needs, and  answer any questions you may have. Enter your details and we'll get back to you shortly. </h2>
        <%= form_for @message, url: home_send_message_path, method: :post, html: {id: "new_contact_message"} do |f| %>
        <%= render 'shared/errors', object: @message %>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control" , placeholder: "Name", required: true,"data-msg-required": "Name Required" %>
        </div>

        <div class="form-group">
          <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true, email: true, "data-msg-required": "Email Required"%>
        </div>

        <div class="form-group">
          <%= f.text_area :body, rows: 15, class: "form-control", placeholder: "Message..", required: true, "data-msg-required": "Message Required" %>
        </div>

        <%= f.submit "Send", class: "btn btn-main"%>
        <% end %>
      </div>


      <div class="col-sm-6">
        <div class="mt80">
          <h3> <img src="/assets/place.png"> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
          <h3> <img src="/assets/phone.png"> +12 12345 123456</h3>
          <h3> <img src="/assets/email2.png"> sample@sample.com</h3>

          <ul>
            <li><i class="fab fa-facebook-f"></i></li>
            <li><i class="fab fa-pinterest-p"></i></li>
            <li><i class="fab fa-twitter"></i></li>
            <li><i class="fab fa-youtube"></i></li>
            <li><i class="fab fa-linkedin-in"></i></li>
            <li><i class="fab fa-vimeo-v"></i></li>
            <li><i class="fab fa-google-plus-g"></i></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $("#new_contact_message").validate();
</script>

app/views/home/get_sellers.js.erb
$("#comparator_page").html("<%= j render(partial: 'seller_comparator',locals: {category: @category, sellers: @sellers}) %>");

app/views/home/home_page.html.erb
<div class="home-wrap">
  <img src="/assets/home-banner.png" width="100%">
  <div class="container">
    <div class="row" style="margin-top: 3em; margin-bottom:3em; ">

      <div class="col-sm-3">
        <div class="home-box">
          <img class="bx-img" src="assets/tp-box-logo.png" width="85%">

           <img class="home-pro mt20" src="/assets/sample.png" width="100%">
           <%= link_to "ASK REQUEST", select_category_orders_path, class: "btn btn-block btn-re-box" %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="home-box">
          <img class="bx-img" src="assets/tp-box-logo.png" width="85%">

           <img class="home-pro mt20" src="/assets/sample.png" width="100%">
           <%= link_to "ASK REQUEST", select_category_orders_path, class: "btn btn-block btn-re-box" %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="home-box">
          <img class="bx-img" src="assets/tp-box-logo.png" width="85%">

           <img class="home-pro mt20" src="/assets/sample.png" width="100%">
           <%= link_to "ASK REQUEST", select_category_orders_path, class: "btn btn-block btn-re-box" %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="home-box">
          <img class="bx-img" src="assets/tp-box-logo.png" width="85%">

           <img class="home-pro mt20" src="/assets/sample.png" width="100%">
           <%= link_to "ASK REQUEST", select_category_orders_path, class: "btn btn-block btn-re-box" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/how_it_works.html.erb
<div class="compat">
  <div class="container">
    <%= video_tag "/assets/tradepack.mp4", :width => "100%", :controls => true %>
  </div>
</div>