config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: 'users'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'devise/registrations#new'
  end
  devise_for :admins, :skip => [:registrations], path: 'admins'
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  namespace :admin do
    resources :sellers, only:[:new, :index, :create, :edit, :update, :destroy, :show] do
      collection do
        get 'states'
        get 'load_size_values'
      end
    end
    resources :pallets, only: [:update]
    resources :categories, only:[:new, :index, :create, :edit, :update, :destroy] do
      collection do
        get "load_size_types"
      end
    end
    resources :dashboard, only:[:index]
    #resources :products, only:[:index, :new, :create, :edit, :update, :show]
    resources :option_types, only:[:index, :new, :create, :edit, :update]
    resources :users, only: [:index, :show] do
      member do
        get 'approve'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      member do
        get 'cancel_order'
        get 'paid_order'
        get 'change_delivery_status'
      end
      collection do
        get 'public_orders', as: "public"
      end
    end
    root to: "categories#index"
    # get 'sellers/states'
  end
  resource :user, only: [:edit, :update] do
    collection do
      get "new_address"
      post "create_address"
      get "edit_address"
      patch "update_address"
      get 'delete_address'
    end
  end
  resources :notifications, only:[:index]
  resources :orders, only: [:new, :create] do
    collection do
      get 'select_category'
      get 'my_requests'
      get 'my_orders'
      post "hook"
      get 'order_summary'
      get 'order_canceled'
      get 'get_pallet'
      get 'ask_with_comparator'
    end
    member do
      get 'cancel_order', as: "cancel"
      get 'invoice'
      get 'offer_summary'
    end
  end
  get '/orders', to: 'orders#my_requests'
  get 'categories/index'
  get 'categories/states'
  get '/home/contact_us'
  get '/home/privacy'
  get '/home/faq'
  get '/home/how_it_works'
  get '/home/home_page'
  get '/home/comparator'
  get '/home/get_sellers'
  post '/home/send_message'

  root to: "home#home_page"
  match '*path', via: :all, to: redirect('/404')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_ancestry
  validates :title, :image, :size_type, presence: true
  mount_uploader :image, ImageUploader
  has_many :category_option_types
  has_many :option_types, through: :category_option_types, dependent: :destroy
  has_many :category_sellers
  has_many :sellers, through: :category_sellers, dependent: :destroy
  has_many :orders
  has_many :option_values, through: :option_types
  has_many :pallets
  belongs_to :size_type, class_name: "OptionType", foreign_key: "size_id"
  validates_size_of :image, maximum: 0.5.megabytes.to_i, message: "should be less than 500KB"
  after_update :update_pallets
  before_destroy :delete_pallets

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def size_values
    size_type.option_values
  end

  def pallet_sellers
    sellers.joins(:pallets).where("pallets.pallet_size > ? AND pallets.category_id = ?", 0, self.id).distinct
  end

  def self.size_categories
    Category.joins(:pallets).where("pallets.pallet_size > ?", 0).distinct
  end

  def title_to_upper
    self.title.upcase
  end

  # def self.ancestry_options(items)
  #   result = []
  #   items.map do |item, sub_items|
  #     result << [yield(item), item.id]
  #     #this is a recursive call:
  #     result += ancestry_options(sub_items) {|i| "#{'-' * i.depth} #{i.title.titleize}" }
  #   end
  #   result
  # end

  # def update_pallets(option_type)
  #   self.sellers.each do |seller|
  #     self.size_values.each do |value|
  #       Pallet.find_or_create(seller_id: seller.id, option_value_id: value.id, category_id: self.id)
  #     end
  #   end
  # end

  def update_pallets
    if size_id_changed?
      @pallets = Pallet.where(category_id: self.id)
      @pallets.destroy_all if @pallets.present?
      self.sellers.each do |seller|
        seller.update_pallets(self)
      end
    end
  end
 private

  def delete_pallets
    pallets = Pallet.where(category_id: self.id)
    pallets.destroy_all if pallets.present?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  load_and_authorize_resource

  def index
    @categories = Category.all.order(created_at: :desc)
  end

  def new
    @category = Category.new
    #@categories = Category.ancestry_options(Category.unscoped.arrange(:order => 'title')) {|i| "#{'-' * i.depth} #{i.title.titleize}" }
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
    #@categories = Category.ancestry_options((Category.where.not(id: @category.id)).arrange(:order => 'title')) {|i| "#{'-' * i.depth} #{i.title.titleize}" }
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render "edit"
    end
  end

  def load_size_types
    @option_types = OptionType.find(params[:ids])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "Category deleted"
    redirect_to admin_categories_path
  end

  private


  def category_params
    params.require(:category).permit(:title, :image, :size_id, {option_type_ids: []})
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "frontend"
  #load_and_authorize_resource

  def index
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_categories.html.erb
          <% collection.each_with_index do |cat, i| %>

            <ul class="treeview checklist">
              <li>
                <input type="checkbox" name="tall" id="tall-<%=cat.id%>">
                <label for="tall-<%=cat.id%>">
                  <div class="ball" data-id="<%=i+1%>"></div>
                  <span ><%=cat.title%> <%=link_to '<i class="edit-pencil fa fa-pencil-square-o pull-right"></i>'.html_safe, edit_admin_category_path(cat)%></span>
                </label>
                <% if cat.has_children? %>
                    <%= render partial: "child_category", locals: { children: cat.children } %>
                <% end %>
              </li>
            </ul>
          <% end %>

app/views/admin/categories/_child_category.html.erb
<% children.each_with_index do |cat, i| %>

            <ul >
              <li>
                <input type="checkbox" name="tall" id="tall-<%=cat.id%>">
                <label for="tall-<%=cat.id%>">
                  <div class="ball" data-id="<%=i+1%>"></div>
                  <span ><%=cat.title%> <%=link_to '<i class="edit-pencil fa fa-pencil-square-o pull-right"></i>'.html_safe, edit_admin_category_path(cat)%></span>
                </label>
                <% if cat.has_children? %>
                    <%= render partial: "child_category", locals: { children: cat.children } %>
                <% end %>
              </li>
            </ul>
          <% end %>

app/views/admin/categories/edit.html.erb
  <div class="container-fluid">
    <div class="page-toolbar">
      <div class="page-toolbar-block">
        <div class="page-toolbar-title">Edit Category</div>
        <div class="page-toolbar-subtitle"></div>
      </div>

      <ul class="breadcrumb">
        <li><a href="<%= admin_root_path %>">Dashboard</a></li>
        <li class="active">Edit Category</li>
      </ul>
    </div>

    <div class="clearfix"></div>

    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="page-bg">
          <div class="row m0">
            <div class="col-sm-6 col-sm-offset-3">
              <%= form_for @category, url: admin_category_path(@category), method: :put, html: {id: "edit_category"} do |f| %>
                <%= render 'shared/errors', object: @category %>
                <div class="form-group">
                  <label>Category Title:</label>
                  <%= f.text_field :title, class: "form-control", placeholder: "Category Title", required: true, "data-msg-required": "Please enter category title", maxlength: 50%>
                </div>
                <div class="form-group">
                  <label>Option Types:</label>
                  <%= f.collection_select :option_type_ids, OptionType.all, :id, :name, {}, {class: "form-control selectpicker", multiple: true, required: true, "data-msg-required": "Please select option types", id: "select_option_type"} %>
                </div>

                <div class="form-group">
                  <label>Option Type for setting pallet size:</label>
                  <%= f.collection_select :size_id, @category.option_types, :id, :name, {prompt: "Select one option type"}, {class: "form-control", required: true, "data-msg-required": "Please select option type", id: "select_size_id"} %>
                </div>
                <div class="form-group">
                  <label>Image:</label>
                  <%= f.file_field :image, class: "form-control", required: f.object.image? ? false : true, accept: "image/png, image/jpg, image/jpeg" %>
                </div>

                <div align="right">
                  <%= link_to "CANCEL", admin_categories_path, class: "btn btn-default" %>
                  <%= f.submit "SAVE", class: "btn btn-primary" %>
                </div>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  $(document).ready(function(){
     $("#edit_category").validate();
  });
  $(".selectpicker").on('hidden.bs.select', function() {
    var ids = $('.selectpicker').val();
    $.ajax({
      url: "/admin/categories/load_size_types",
      type: 'GET',
      data: {ids: ids }
    });
  });
</script>

app/views/admin/categories/index.html.erb
    <div class="container-fluid">

      <div class="page-toolbar">

        <div class="page-toolbar-block">
          <div class="page-toolbar-title"> Category List</div>
          <div class="page-toolbar-subtitle"></div>
        </div>

        <ul class="breadcrumb">
          <li><a href="<%= admin_root_path %>">Dashboard</a></li>
          <li class="active">Categories</li>
        </ul>

      </div>

      <div class="clearfix"></div>

      <div class="page-wrapper">
        <div class="container-fluid">
          <table class="table list">
          <thead>
            <tr>
              <th>Image</th>
              <th>Category Name</th>
              <th> No of option Types</th>
              <th>No of sellers</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= image_tag(category.image.url, class: "img-rounded", width: 40, height: 40)%></td>
                <td><%= category.title.titleize%></td>
                <td><%= category.option_types.count%></td>
                <td><%= category.sellers.count%></td>
                <td><span><%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_admin_category_path(category) %>&nbsp;
                  <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"}%></span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        </div>

      </div>
    </div>
  </div>

app/views/admin/categories/load_size_types.js.erb
$("#select_size_id").html("<%= j options_for_select( @option_types.collect { |d| [d.name, d.id] }) %>");

app/views/admin/categories/new.html.erb
  <div class="container-fluid">
    <div class="page-toolbar">
      <div class="page-toolbar-block">
        <div class="page-toolbar-title">New Category</div>
        <div class="page-toolbar-subtitle"></div>
      </div>

      <ul class="breadcrumb">
        <li><a href="<%= admin_root_path %>">Dashboard</a></li>
        <li class="active">New Category</li>
      </ul>
    </div>

    <div class="clearfix"></div>

    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="page-bg">
          <div class="row m0">
            <div class="col-sm-6 col-sm-offset-3">
              <%= form_for @category, url: admin_categories_path, method: :post, html: {id: "new_category"} do |f| %>
              <%= render 'shared/errors', object: @category %>
                <div class="form-group">
                  <label>Category Title:</label>
                  <%= f.text_field :title, class: "form-control", placeholder: "Category Title", required: true, "data-msg-required": "Please enter category title", maxlength: 50%>
                </div>
                <div class="form-group">
                  <label>Option Types:</label>
                  <%= f.collection_select :option_type_ids, OptionType.all, :id, :name, {}, {class: "form-control selectpicker", multiple: true, required: true, "data-msg-required": "Please select option types", id: "select_option_type"} %>
                </div>

                <div class="form-group">
                  <label>Option Type for setting pallet size:</label>
                  <%= f.select :size_id, {}, {prompt: "Select one option type"}, {class: "form-control", required: true, "data-msg-required": "Please select option type", id: "select_size_id"} %>
                </div>

                <div class="form-group">
                  <label>Image:</label>
                  <%= f.file_field :image, class: "form-control", required: true, accept: "image/png, image/jpg, image/jpeg" %>
                </div>

                <div align="right">
                  <%= link_to "CANCEL", admin_categories_path, class: "btn btn-default" %>
                  <%= f.submit "SAVE", class: "btn btn-primary" %>
                </div>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  $(document).ready(function(){
     $("#new_category").validate();
  });
  $(".selectpicker").on('hidden.bs.select', function() {
    var ids = $('.selectpicker').val();
    $.ajax({
      url: "/admin/categories/load_size_types",
      type: 'GET',
      data: {ids: ids }
    });
  });
</script>