config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: 'users'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'devise/registrations#new'
  end
  devise_for :admins, :skip => [:registrations], path: 'admins'
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  namespace :admin do
    resources :sellers, only:[:new, :index, :create, :edit, :update, :destroy, :show] do
      collection do
        get 'states'
        get 'load_size_values'
      end
    end
    resources :pallets, only: [:update]
    resources :categories, only:[:new, :index, :create, :edit, :update, :destroy] do
      collection do
        get "load_size_types"
      end
    end
    resources :dashboard, only:[:index]
    #resources :products, only:[:index, :new, :create, :edit, :update, :show]
    resources :option_types, only:[:index, :new, :create, :edit, :update]
    resources :users, only: [:index, :show] do
      member do
        get 'approve'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      member do
        get 'cancel_order'
        get 'paid_order'
        get 'change_delivery_status'
      end
      collection do
        get 'public_orders', as: "public"
      end
    end
    root to: "categories#index"
    # get 'sellers/states'
  end
  resource :user, only: [:edit, :update] do
    collection do
      get "new_address"
      post "create_address"
      get "edit_address"
      patch "update_address"
      get 'delete_address'
    end
  end
  resources :notifications, only:[:index]
  resources :orders, only: [:new, :create] do
    collection do
      get 'select_category'
      get 'my_requests'
      get 'my_orders'
      post "hook"
      get 'order_summary'
      get 'order_canceled'
      get 'get_pallet'
      get 'ask_with_comparator'
    end
    member do
      get 'cancel_order', as: "cancel"
      get 'invoice'
      get 'offer_summary'
    end
  end
  get '/orders', to: 'orders#my_requests'
  get 'categories/index'
  get 'categories/states'
  get '/home/contact_us'
  get '/home/privacy'
  get '/home/faq'
  get '/home/how_it_works'
  get '/home/home_page'
  get '/home/comparator'
  get '/home/get_sellers'
  post '/home/send_message'

  root to: "home#home_page"
  match '*path', via: :all, to: redirect('/404')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :default_address_values, on: [:create]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  #before_create :set_default_role
  belongs_to :role, required: false
  has_many :addresses, as: :addressable, dependent: :destroy
  has_one :primary_address, -> { where(address_type: "primary") }, as: :addressable, class_name: "Address"
  has_many :orders
  accepts_nested_attributes_for :addresses
  accepts_nested_attributes_for :primary_address
  validates :first_name, :last_name, :phone_no, :company, :vat_no, :phone_no, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates_format_of :phone_no, :with =>  /(?:\+?|\b)[0-9]\b/
  mount_uploader :image, ImageUploader
  validates_size_of :image, maximum: 0.5.megabytes.to_i, message: "should be less than 500KB"
  VAT_COUNTRIES = ['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE','GB']

  def full_name
    [first_name, last_name].join(" ").titleize
  end

  def default_address
    primary_address || addresses.first
  end

  def vat
    [vat_code, vat_no].join.upcase
  end

  private
    def set_default_role
      self.role ||= Role.find_by_name('buyer')
    end

    def default_address_values
      self.primary_address.name = self.first_name
      self.primary_address.phone_no = self.phone_no
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.includes(:primary_address).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @address = @user.default_address
  end

  def approve
    @user = User.find(params[:id])
    @user.update(approved: true)
    UserMailer.approved(@user).deliver_now
    flash[:notice] = "User approval successfull"
    redirect_to admin_user_path(@user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # layout 'frontend', only: [:edit, :update]
  # layout 'user_devise', only: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({})
    resource.build_primary_address
    respond_with self.resource
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :new_address, :create_address]
  layout "frontend"

  def edit
    @user
    @addresses = @user.addresses.order(created_at: :desc)
  end

  def update
    if @user.update(edit_params)
      flash[:notice] = "Profile Successfully Updated"
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end

  def edit_address
    @address = Address.find(params[:id])
    country = @address.country
    @country = CS.countries.select{ |x,y| y == country }.first[0]
  end

  def update_address
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:success] = "Address updated"
      redirect_to edit_user_path
    else
      render :edit_address
    end
  end

  def new_address
    @user
    @address = @user.addresses.build
  end

  def create_address
    @user
    @address = @user.addresses.build(address_params)
    if @address.save
      flash[:success] = "Address Crated"
      redirect_to edit_user_path
    else
      render :new_address
    end
  end

  def delete_address
    @address = Address.find(params[:id])
    @address.destroy
    flash[:success] = "Address Deleted"
    redirect_to edit_user_path
  end

  private

  def set_user
    @user = current_user
  end

  def address_params
    params.require(:address).permit(:name, :phone_no, :address1, :address2, :city, :state, :country, :zip)
  end

  def edit_params
    params.require(:user).permit(:first_name, :last_name, :vat_no, :vat_code, :phone_no, :company, :image, addresses_attributes: [:address1, :address2,
      :city, :state, :country, :zip])
  end
end

app/views/admin/users/index.html.erb
  <div class="container-fluid">

    <div class="page-toolbar">

      <div class="page-toolbar-block">
        <div class="page-toolbar-title"> Users List</div>
        <div class="page-toolbar-subtitle">Subtitle</div>
      </div>

      <ul class="breadcrumb">
        <li><a href="<%= admin_root_path %>">Dashboard</a></li>
        <li class="active">Users</li>
      </ul>

    </div>

    <div class="clearfix"></div>

    <div class="page-wrapper">
      <div class="container-fluid">

        <%= search_form_for @q, url: admin_users_path do |f| %>
          <div class="col-sm-3">
            <%= f.search_field :first_name_or_last_name_or_email_cont, placeholder: "Name or Email", class: "form-control" %>
          </div>
          <div class="col-sm-3">
            <%= f.search_field :primary_address_country_cont, placeholder: "Country", class: "form-control"  %>
          </div>
          <div class="col-sm-3">
            <%= f.search_field :company_cont, placeholder: "Company", class: "form-control"  %>
          </div>
            <div class="col-sm-3 mb20">
              <%= link_to request.path, class: "btn btn-primary " do %>
                <i class="fas fa-filter"></i> Clear Filter
              <% end %>
              <%= f.button :submit, class: "btn btn-success ml10" do %>
                <i class='fas fa-search'></i> Search
              <% end %>
            </div>
        <% end %>


        <table class="table list">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Company</th>
              <th>VAT Number</th>
              <th>Country</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to "#{user.full_name}", admin_user_path(user) %></td>
                <td><%= user.email %></td>
                <td><%= user.phone_no %></td>
                <td><%= user.company.titleize %></td>
                <td><%= user.vat_no %></td>
                <td><%= user.try(:default_address).try(:country) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>

app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="users-view">
        <div align="center">
          <img src="/assets/user23.png" width="180px" class="mb20" />
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Name</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @user.full_name.titleize%></p>
          </div>
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Email</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @user.email%></p>
          </div>
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Company</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @user.company.titleize%></p>
          </div>
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Phone Number</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @user.phone_no%></p>
          </div>
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Vat Number</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @user.vat%></p>
          </div>
        </div>

        <div class="row m0 border-dashed pt10">
          <div class="col-sm-6">
            <p > <b>Address</b> <span class="pull-right" >: </span> </p>
          </div>
          <div class="col-sm-6">
            <p ><%= @address.full_address%></p>
          </div>
        </div>

        <% if !@user.approved? %>
        <div align="center" class="mt20">
          <%= link_to "Cancel", admin_users_path, class: "btn btn-default"%>
          <%= link_to "Approve", approve_admin_user_path, class: "btn btn-primary"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>